#ifndef GRAPHIC
#define GRAPHIC

#define LINE_HEIGHT 20 
#define LEFT_PADDING 10
#define RIGHT_PADDING 10
#define PADDING LEFT_PADDING + RIGHT_PADDING
#define BUTTON_WIDTH 100
#define LINE_GAP 3
#define LIST_MAX_ELEMENT_ON_SCREEN_OFFSET 12

#endif
